blog/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from blog import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^category/(?P<id>\d+)/$', views.blogs, name='category'),
    url(r'^blogs/$', views.blogs, name='blogs'),
]

cycle/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from cycle.views import CycleTransactionCreate
from cycle import views

urlpatterns = [
    path('', CycleTransactionCreate.as_view(), name=''),
    path('CycleTransactionGet', views.CycleTransactionGet, name='CycleTransactionGet'),
    path('saveData', views.saveData, name='saveData'),

    path('sample_size', views.sample_size, name='sample_size'),
    path('upload_sample', views.upload_sample, name='upload_sample'),
    path('sugg_samples', views.sugg_samples, name='sugg_samples'),
    path('deficiency', views.deficiency, name='deficiency'),
    path('report_form', views.report_form, name='report_form'),

    url(r'^(?P<id>\d+)/edit/$', views.TOC_update, name='TOC_update'),
    url(r'^xml_to_table/$', views.xml_to_table, name='xml_to_table'),
    url(r'^savegraph/$', views.savegraph, name='savegraph'),
    url(r'^loadgraph/$', views.loadgraph, name="loadgraph"),
    url(r'^grapheditor/$', views.grapheditor, name='grapheditor'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    re_path(r'^cycle/', include('cycle.urls')),
    re_path(r'^blog/', include('blog.urls')),
    re_path('admin/', admin.site.urls),
]

cycle/models.py
from django.db import models
from picklefield.fields import PickledObjectField
import numpy


class Client(models.Model):
    client_name = models.CharField(max_length=20)

    def __str__(self):
        return self.client_name


class Cycle(models.Model):
    cycle_type = models.CharField(default='sales', max_length=15)
    client_name = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cycle_type)


class Cycle_in_obj(models.Model):
    Option_CHOICES = (
        (2019, 2019),
        (2020, 2020),
    )
    cycle_type = models.ForeignKey(Cycle, on_delete=models.CASCADE)
    #user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    client_name = models.ForeignKey(Client, on_delete=models.CASCADE)
    year = models.IntegerField(choices=Option_CHOICES)

    class Meta:
        unique_together = ('cycle_type', 'client_name', 'year', )


class Objectives(models.Model):  # Build

    medium = 'Med'
    low = 'Low'
    high = 'High'

    Med_High_CHOICES = (
        (medium, 'Med'),
        (low, 'Low'),
        (high, 'High'),
    )

    cycle = models.ForeignKey(
        Cycle_in_obj, related_name="has_objectives", on_delete=models.CASCADE)
    transaction_objective = models.CharField(max_length=100, unique=True)
    assessed_cr = models.CharField(max_length=20, choices=Med_High_CHOICES)


class DatafileModel(models.Model):
    cycle = models.ForeignKey(Cycle, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    data = PickledObjectField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        ordering = ["updated", "pk"]

    def __str__(self):
        return str(self.data)


class testing_of_controls(models.Model):
    Option_CHOICES = (
        ('deficient', 'deficient'),
    )
    cycle = models.ForeignKey(Cycle, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    data = models.ForeignKey(DatafileModel, on_delete=models.CASCADE)
    remarks = models.TextField(null=True)
    attachment = models.FileField(null=True, blank=True)
    deficient = models.CharField(max_length=8, choices=Option_CHOICES)

    def __str__(self):
        return str(self.data)


class Mxcell(models.Model):  # Case
    style = models.CharField(max_length=1000)
    value = models.CharField(max_length=1000)
    # objectives = models.ManyToManyField(Objectives)
    objectives = models.ManyToManyField(Objectives)

    # XXX Cycle
    # XXX client
    # XXX get

    def __str__(self):
        return self.value


class Test_of_Controls(models.Model):
    mxcell = models.ForeignKey(Mxcell, on_delete=models.CASCADE)
    control_procedures = models.CharField(max_length=150)
    cycle_in_obj = models.ForeignKey(Cycle_in_obj, on_delete=models.CASCADE)

    def __str__(self):
        return self.control_procedures


class sampling(models.Model):
    Estimated_Population_Exception_Rate = models.IntegerField()
    # EPER - Exception Rate that the auditor expects to find in the population
    Tolerable_Exception_Rate = models.IntegerField()
    # TPER - Exception Rate that the auditor will permit in the population and still be willing to conclude that -
    # - controls are operating effectively
    Population_Size = models.IntegerField()
    Suggested_Sample_Size = models.IntegerField()
    Actual_Sample_Size = models.IntegerField()  # page-525
    Number_of_Exceptions = models.IntegerField(null=True)
    Sample_Exception_Rate = models.IntegerField(null=True)
    # Number of exceptions in sample divided by the sample size
    Computed_Upper_Exception_Rate = models.IntegerField(null=True)
    # The higest estimated exception rate in the population at a given ARACR
    Client = models.ForeignKey(Client, on_delete=models.CASCADE)
    Cycle = models.ForeignKey(Cycle, on_delete=models.CASCADE)
    Year = models.IntegerField(null=True)


class samples(models.Model):

    samples = models.FileField(null=True, blank=True)
    Actual_Sample_Size = models.ForeignKey(
        Test_of_Controls, related_name="Actual_Sample_Size", on_delete=models.CASCADE)

    Random = 'Random'
    Condition = 'Condition'
    Weights = 'Weights'

    Sampling_CHOICES = (
        (Random, 'Random'),
    )
    sampling_method = models.CharField(max_length=20, choices=Sampling_CHOICES)

    def __str__(self):
        return str(self.samples)


class Deficiency(models.Model):
    cycle = models.ForeignKey(Cycle, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    remarks = models.TextField(null=True)
    financials = models.TextField(null=True)
    suggestions = models.TextField(null=True)
    datafile = models.ForeignKey(DatafileModel, on_delete=models.CASCADE)
    is_active = models.BooleanField()

    def __str__(self):
        return str(self.remarks)


class Report(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    year = models.IntegerField()
    intro_paragraph = models.TextField(null=True)
    audit_objective = models.TextField(null=True)
    scope_paragraph = models.TextField(null=True)
    deficiency = models.TextField(null=True)
    financials = models.TextField(null=True)
    suggestions = models.TextField(null=True)
    opinion_paragraph = models.TextField(null=True)

    def __str__(self):
        return str(self.intro_paragraph)

    # mxgraph


class Title(models.Model):
    title = models.TextField(null=True)

    def __str__(self):
        return self.title


class XMLGraph(models.Model):
    #  only one title per graph
    title = models.OneToOneField(
        to=Title,
        blank=True,
        null=True,
        on_delete=models.CASCADE)

    XMLGraph = models.TextField(null=True)
    # user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user = models.CharField(max_length=20)
    cycle_in_obj = models.ForeignKey(Cycle_in_obj, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.XMLGraph)

    class Meta:
        unique_together = ('XMLGraph', 'cycle_in_obj',)


class Member(models.Model):
    XMLGraph = models.ForeignKey('XMLGraph',
                                 null=True,
                                 on_delete=models.CASCADE)
    # username = models.CharField(max_length=50)
    # user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user = models.CharField(max_length=20)

    def __str__(self):
        return self.user


class Profile(models.Model):
    user = models.OneToOneField(
        to=Member,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Procedures(models.Model):
    cycle = models.ForeignKey(Cycle, on_delete=models.CASCADE)
    activity = models.TextField(null=True)
    procedure = models.TextField(null=True)

    def __str__(self):
        return self.procedure

cycle/templates/cycle_form.html
{% extends "base.html" %}

{% block content %}

		<main class="transaction-page">
      <section class="inner-wrap">
        <div class="video">
            <video autoplay loop src="video/video.mp4" type="video/mp4">
            </video>
        </div>
        <div class="overlay"></div>

          {% include 'sidebar.html' %}

				  <div class="general_form">
            <div class="btn-box flex flex-column flex-vertical-bottom flex-sd-row flex-end">
                <button class="general_btn">New Client
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <button class="general_btn">New Cycle
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
           
					
          <form method="post">   
                   
            <h3 class="general_title">Transaction Objective</h3>
					
                {% csrf_token %}
                <div class="dropdown-box flex flex-sb flex-vertical-top">
                {% for field in form.visible_fields %}
                  <div class="general_dropdown-list">
                      {{ field }}
                  </div>
                {% endfor %}                
                </div>

                <table class="table">
                    {{ titles.management_form }}
                    {% for form in titles.forms %}
                    <tr class="{% cycle row1 row2 %} formset_row">
                    {% for field in form.visible_fields %}
                    <td>       {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
                                    <div class="input_box">
                                        {{ field }}
                                    </div>
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
				</div>
			</section>
		</main>
    <script src="/static/js/jquery.formset.js"></script>
	  <script src="/static/js/script.js"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'add objectives',
            deleteText: 'remove',
            prefix: 'has_objectives',
        });
    </script>
    <script>

      let index = 1

      $("body").on('change', 'select', function (event) {
        event.preventDefault()
        event.stopPropagation()
        var cycle_type = $("#id_cycle_type").val();
        var client_name =  $("#id_client_name").val();
        var year = $("#id_year").val()

        $.ajax({
          url: '{% url "CycleTransactionGet" %}',
          type: "get",
          data: {
            'cycle_type' : cycle_type,
            'client_name': client_name,
            'year': year
          },
          success: function(response, status) {
              console.log(response.data);
              $(".formset_row").remove()
              for (i = 0; i < response.data.length; i++) {
                $('.add-row').click()
                $("#id_has_objectives-" + index + "-transaction_objective").val(response.data[i]);              
                index++;
              }
          }
        });
        
      });
      
    </script>

  {% endblock content %}

cycle/templates/pdf.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Title</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
                padding: 25px 20px 0px 20px;  
            }
            .sub-title {
              font-size: 16px;
              font-weight: 200;
              color: #999;
              text-align: right;
              margin-bottom: 0px;
              padding-bottom: 0;
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Audit of Internal Controls over Financial Reporting</p>
                <p class="sub-title">{{year}} by {{client}}</p>
            </div>
        <div>
        <div class='details'>
            <hr class='hrItem' />
            <h4>Introductory Paragraph</h4>           
            <p>{{intro_paragraph}}</p>

            <h4>Audit Objective</h4>       
            <p>{{audit_objective}}</p>

            <h4>Scope Paragraph</h4>
            <p>{{scope_paragraph}}</p>

            <hr class='hrItem' />

            <h3>Findings and Recommendations</h3>
            <h5>Remarks</h5>
            <p>{{remarks}}</p>
            <h5>Financial Statements</h5>
            <p>{{financials}}</p>
            <h5>Suggested Improvements</h5>
            <p>{{suggestions}}</p>
            <hr class='hrItem' />
            <h4>Opinion Paragraph</h4>
            <p>{{opinion_paragraph}}</p>
            <br/>
            <p>Signature</p>

            <p>Date</p>
           
        </div>
    </div>
    </body>
</html>

cycle/templates/sample_form.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}


{% block content %}
<style>
.defecient label {
  pointer-events: auto;
}
.defecient .controls {
  display: flex;
}
.defecient .radio:first-of-type {
  margin-right: 20px;
}
.submit-btn {
  margin-right: auto; 
  margin-left: 0;
}
.support-thumbnails {
  margin-left: 30%;
  width: 70%;
  margin-bottom: 20px;
}
.thumb-image {
    width: 100px;
    height: 100px;
    border: 1px dashed #666;
    padding: 5px;
    margin: 5px;
}
.control-procedures > p {
  padding: 5px;
  margin: 0px 20px;
}
</style>
<main class="transaction-page">
    <section class="inner-wrap">
        {% include 'sidebar.html' %}
        <div class="sampling_form">
                <input id="submitted" type="hidden" value="{{submitted}}" />
                <form action="" id="sample_form" method="post" enctype="multipart/form-data">
                  <div class="modal-header" style="margin-top: 50px; text-align: right">
                      <h4 class="modal-title">Test Of Controls</h4>
                  </div>
                  <div class="sampling_data">
                      <span>Cycle: {{sampling_data.Cycle}}</span>
                      <span>Client: {{sampling_data.Client}}</span>
                      <span>Year: {{sampling_data.Year}}</span>
                  </div>
                  <table>
                    <thead>
                      <tr>
                       <th>{{instance.data }}</th>
                      </tr>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                  {% csrf_token %}
                    {{ form.non_field_errors }}
                    {{ form.deficient.errors }}
                    <div class="defecient"> 
                      {{ form.deficient|as_crispy_field }}
                    </div>
                    {{ form.attachment.errors }}
                    {{ form.attachment|as_crispy_field }}
                    {{ form.remarks.errors }}
                    {{ form.remarks|as_crispy_field }}
                    <div class="control-procedures">
                      {% for p in procedures %}
                        <p>Control Procedures-{{ forloop.counter }}</p>
                        <p>{{p.control_procedures}}</p>
                        {% empty %}
                        <p>No Control Procedures</p>
                      {% endfor %}
                      
                    </div>
                    <div class="support-thumbnails">
                        
                    </div>

                    <div class="modal-footer" style="display: flex; text-align: center;">
                            <button class="general_btn" id="saveBtn">Save
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                            </button>
                            <button class="general_btn" id="prevBtn" data-sample="{{ the_prev.id }}"  style="margin-left: 25px" data-url="/cycle/{{ the_prev.id }}/edit/">Previous Sample
                              <span></span>
                              <span></span>
                              <span></span>
                              <span></span>
                            </button>    
                            <button class="general_btn" id="nextBtn" data-sample="{{ the_next.id }}" data-url="/cycle/{{ the_next.id }}/edit/">Next Sample
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                            </button>                   
                    </div>
                </form>     
             
        </div>
    </section>
</main>
<!-- {{the_next}}
 -->
<!-- {% with next=instance.get_next_by_data %}
    {% if next %}
        <a href="{% url 'TOC_update' id=obj.id %}">next</a>
    {% endif %}
{% endwith %} -->

<!-- {% if the_next %}
<a href="{% url 'TOC_update' the_next.id %}">Next</a>
{% else %}
This is the last film!
{% endif %} -->
<script>
  $(function() {
      
      if ($("#submitted").val() == "True") {
        $("#submitted").val("False")        
        if (!$("#nextBtn").hasClass("btn-disabled")) {
            document.location.href = $("#nextBtn").data("url");
        } else {
            document.location.href = '{% url "deficiency" %}';            
        }
      }
      var $radios = $('input:radio[name=deficient]');
      if($radios.is(':checked') === false) {
          $radios.filter('[value=deficient]').prop('checked', true);
      }
  });

  var nextId = $("#nextBtn").data("sample")
  var prevId = $("#prevBtn").data("sample")

  if (nextId.length == 0) {
    $("#nextBtn").addClass("btn-disabled");
  }
  if (prevId.length == 0) {
    $("#prevBtn").addClass("btn-disabled");
  }

  const saveSample = function () {
    const params = {
      deficient: $("input[name=deficient]:checked").val(),
      datafile_id: '{{instance.id}}',
      remarks: $("#id_remarks").val(),
      islast: $("#nextBtn").hasClass("btn-disabled") ? true : false
    }
    const csrftoken = $("[name=csrfmiddlewaretoken]").val();
    
    $.ajax({
      url: '{% url "deficiency" %}',
      type: 'post',
      headers: { "X-CSRFToken": csrftoken },
      data: params,
      success: function (res) {
        console.log(res)
        if(res.message == "success"){          
          if(res.url != ""){
            document.location.href = '{% url "deficiency" %}';
            return;
          }
          $('form#sample_form').submit()
        }
      }, error: function (res) {
        console.log(res)
      }
    })
  }
  $(".general_btn").on('click', function (event) {
    event.preventDefault();
    
    if (($(this).attr("id") == "saveBtn" && !$(this).hasClass("btn-disabled")) || ($(this).attr("id") == "nextBtn" || !$(this).hasClass("btn-disabled"))) {        
        saveSample();
    }
    else if ($(this).attr("id") == "prevBtn" && !$(this).hasClass("btn-disabled")) {      
      document.location.href = $(this).data("url");
    }
  });

  $("input[type=radio]").on('click', function () {
    console.log($(this).val())
    //if ($(this).val() == "defecient" && $("#saveBtn").hasClass('btn-disabled')) 
    //    $("#saveBtn").removeClass('btn-disabled') 
    //else if (!$("#saveBtn").hasClass('btn-disabled'))
    //    $("#saveBtn").addClass('btn-disabled')
  });


  $("#sample_form input[type=file]").on('change', function () {
    var count = $(this)[0].files.length;
    var image_holder = $(".support-thumbnails")
    for (var i = 0; i < count; i++) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $("<img />", {
                "src": e.target.result,
                "class": "thumb-image",
            }).appendTo(image_holder);
        };
        reader.readAsDataURL($(this)[0].files[i]);
    }
    
  });
</script>
{% endblock content %}

cycle/templates/sampling.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
 	<main class="transaction-page">
    <section class="inner-wrap">
        {% include 'sidebar.html' %}
        <div class="sampling_form">
          
          <form id="a-good-form-name" method="POST">
              <div class="modal-header" style="margin: 30px; text-align: right">
                <h4 class="modal-title">Sample Size</h4>
              </div>
              <div class="sampling_data" style="text-align: center">
                      <span>Cycle: {{cycle_type}}</span>
                      <span>Client: {{client_name}}</span>
                      <span>Year: {{year}}</span>
              </div>
              <!-- {{ formset.management_form }} -->
              <table class="table table-hover">
                {% csrf_token %}
                <!--thead>
                    <tr>
                      <th> Description of Attributes</th>
                      <th> EPER </th>
                      <th> TER </th>
                      <th> ARACR </th>
                      <th> Suggested Sample Size </th>
                      <th> Actual Sample Size </th>
                  </tr>
                  
              </thead-->
              <tbody>
                <form action="" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                        {{ formset.non_field_errors }}
                        {{ formset.Estimated_Population_Exception_Rate.errors }}
                        {{ formset.Estimated_Population_Exception_Rate|as_crispy_field }}
                        {{ formset.Tolerable_Exception_Rate.errors }}
                        {{ formset.Tolerable_Exception_Rate |as_crispy_field }}
                        {{ formset.Suggested_Sample_Size.errors }}
                        {{ formset.Suggested_Sample_Size|as_crispy_field }}
                        {{ formset.Actual_Sample_Size.errors }}
                        {{ formset.Actual_Sample_Size|as_crispy_field }}
                        {{ formset.Population_Size.errors }}
                        {{ formset.Population_Size|as_crispy_field }}
                </form>
              </tbody>
                  {% if formset.errors %}
                        {% for field in formset.forms %}
                            {% for error in field.errors %}
                                  <div class="alert alert-danger">
                                  <strong>{{ error|escape }}</strong>
                                  </div>
                            {% endfor %}
                          {% endfor %}
                        {% for error in formset.non_field_errors %}
                                  <div class="alert alert-danger">
                                  <strong>{{ error|escape }}</strong>
                                  </div>
                      {% endfor %}
                    {% endif %}
              </table>
              <div class="form-actions">
                <button class="general_btn">Next
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
              </div>
          </form>
        </div>
        <div class='col-sm-6 col-sm-offset-3'>
          {{ result }}
        </div>
    </section>
  </main>

  <script>
    $("#id_Population_Size").change(function () {
      var sample_size = $(this).val();
      var AA = $('#id_Population_Size').val();
      var AB = $('#id_Tolerable_Exception_Rate').val();
      var AC = $('#id_Estimated_Population_Exception_Rate').val();
      console.log(AA);
      console.log(AB);
      console.log(AC);
      var Alpha = 1 - AC;
      var sigma = 0.5;
      

      // var result="";
      // console.log( $(this).val() );

      $.ajax({
        url: '{% url "sugg_samples" %}',
        type: "get",
        data: {
          'sample_size' : sample_size
        },
      
        success: function(data) {
          
          $("#id_Suggested_Sample_Size").replaceWith(data);
          // $("#form-1-Suggested_Sample_Size").replaceWith(data);
          // $("#form-2-Suggested_Sample_Size").replaceWith(data);
          // result = data;
          console.log(data);
        }
      });
    });
  </script>


{% endblock content %}

cycle/templates/select_sample.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
{% load widget_tweaks %}

	<main class="transaction-page">
    <section class="inner-wrap">
        {% include 'sidebar.html' %}
        <div class="sampling_form">
            <form id="sampling_method" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-header" style="margin-top: 50px">
                    <h4 class="modal-title">Select the sampling method and Upload Population file</h4>
                </div>
                <div class="sampling_data">
                    <span>Cycle: {{sampling.Cycle}}</span>
                    <span>Client: {{sampling.Client}}</span>
                    <span>Year: {{sampling.Year}}</span>
                </div>
                <!-- {{ form.sampling_method }}
                {{ form.field_selected }}
                {{ form.field_selected_value }}
                {{ form.samples}} -->
                {% for field in form %}
                    
                    {{ field |as_crispy_field }}
                    
                    {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                   
                {% endfor %}

            <!-- 
            <input type="file" class="btn btn-purple" name="file" >
                                &nbsp;&nbsp;
            <button name="upload_populations" id="upload_population" class="btn btn-purple btn-labeled fa dropzone" >Upload Population</button> -->
        <!--    <div class="form-actions">
                <input type="submit" />
                </div> -->
                <div class="modal-footer" style="margin-top: 30px">
                    <div class="control-group">
                        <label>Sample Attached File To Download</label>
                        <a href="{% static 'resources/Sample_CSV_Upload.csv' %}" style="width: 100%; text-align: right; color: #5080de; padding: 10px;">Click Here</a>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Upload File</label>
                        <div class="controls">
                            <input type="file" class="modal-title" name="file" >
                        </div>
                    </div>
                    <div class="form-group"  style="margin-top: 30px; text-align: right;">
                        <button type="submit" class="general_btn">Select Samples
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>
                        
                </div>

            </form>

 <!--  <form id = "sample-list" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <input type="file" class="btn btn-purple" name="file" >
                        &nbsp;&nbsp;
    <button name="upload_inventory" id="upload_inventory" class="btn btn-purple btn-labeled fa dropzone" >Upload Inventory</button> -->
   <!--  <button type="submit">Upload</button> -->
       {% if form.errors %}
          {% for field in form.forms %}
              {% for error in field.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
              {% endfor %}
            {% endfor %}
          {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
        {% endfor %}
      {% endif %}
  </form>
  </div>
  </section>
</main>

  


     





<head>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>

    <script>
        $(document).ready(function (){
        
            $("#id_sampling_method").change(function() {
                // foo is the id of the other select box 
                if ($(this).val() == "Condition") {
                    $("#id_field_selected").show();
                    $("#id_field_selected_value").show();
                }else{
                    $("#id_field_selected").hide();
                    $("#id_field_selected_value").hide();
                } 
            });
            
            $(function() {
                $("#id_sampling_method").val('Condition');
                // foo is the id of the other select box 
                if ($(this).val() == "Condition") {
                    $("#id_field_selected").show();
                    $("#id_field_selected_value").show();
                }else{
                    $("#id_field_selected").hide();
                    $("#id_field_selected_value").hide();
                } 
            });
        });
    </script>

</head>
{% endblock %}